version: "3.8"

services:
    rabbitmq:
        image: rabbitmq:3-management-alpine
        ports:
            - 5672:5672
            - 15672:15672

    publisher:
        build: ./publisher
        depends_on:
            - rabbitmq
        environment:
            RABBITMQ_HOST: rabbitmq
            RANDOM_NUMBER_QUEUE: random-number-queue

    consumer:
        build: ./consumer
        depends_on:
            - rabbitmq
        environment:
            RABBITMQ_HOST: rabbitmq
            MESSAGE_QUEUE: message-queue

    publisher-consumer:
        build: ./publisher-consumer
        depends_on:
            - rabbitmq
        environment:
            RABBITMQ_HOST: rabbitmq
            RANDOM_NUMBER_QUEUE: random-number-queue
            MESSAGE_QUEUE: message-queue